services:
  relatorio_api:
    build: ./app
    ports:
      - "8000:8000"
    mem_limit: 512m        # Limita o uso de memória para 512 MB
    cpus: 0.5              # Limita a 50% de 1 CPU
    restart: always
    volumes:
      - ./templates:/app/templates
    env_file:
      - .env

  seger_ws:
    build:
      context: ./seger-ws
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # Adicione limites de memória e CPU se necessário
    # mem_limit: 512m
    # cpus: 0.5
    restart: always
    # Adicione volumes se necessário para persistência de dados ou logs
    volumes:
      - ./seger-ws/src:/app/src
      - ./seger-ws/faturas_edp:/app/faturas_edp
    env_file:
      - .env # Se o seger-ws também usa variáveis de ambiente
